-- database structure

CREATE TABLE IF NOT EXISTS "Manager" (
  managerID SERIAL PRIMARY KEY,
  name VARCHAR(50) NOT NULL,
  surname VARCHAR(50) NOT NULL,
  email VARCHAR(80) UNIQUE NOT NULL,
  password VARCHAR(50) NOT NULL 
  );

CREATE TABLE IF NOT EXISTS "Customer" (
  customerID SERIAL PRIMARY KEY,
  name VARCHAR(50) NOT NULL,
  surname VARCHAR(50) NOT NULL,
  email VARCHAR(80) UNIQUE NOT NULL,
  password VARCHAR(50) NOT NULL,
  age INTEGER CONSTRAINT agePositive CHECK (age >= 0)
  arcaneMembership BOOLEAN DEFAULT FALSE,
  phone VARCHAR(10) UNIQUE,
  speciesID INT,
  FOREIGN KEY (speciesID) REFERENCES "Species"(speciesID) ON UPDATE CASCADE
  );

CREATE TABLE IF NOT EXISTS "Wallet" (
  customerID INT PRIMARY KEY,
  CPbalance INT DEFAULT 0 CONSTRAINT positiveBalance CHECK (CPbalance >= 0)
  FOREIGN KEY (customerID) REFERENCES "Customer"(customerID) ON UPDATE CASCADE ON DELETE CASCADE
  );

CREATE TABLE IF NOT EXISTS "Species" (
  speciesID SERIAL PRIMARY KEY,
  name VARCHAR(50) NOT NULL,
  adultAge INT NOT NULL,
  limitAge INT NOT NULL
  );

CREATE TABLE IF NOT EXISTS "Order" (
  
  );
